<a href="https://colab.research.google.com/github/TaisukeOnaka/Taisuke-Onaka/blob/master/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import print_function
import torch

In [0]:
# 初期化されていない5x3行列を作成

In [0]:
x = torch.empty(5, 3)
print(x)

tensor([[1.4624e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.8367e-40]])


In [0]:
# ランダムに初期化された行列を作成

In [0]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5034, 0.2672, 0.7482],
        [0.2401, 0.5310, 0.8231],
        [0.9507, 0.8541, 0.3501],
        [0.3264, 0.4367, 0.6498],
        [0.5931, 0.4884, 0.0056]])


In [0]:
# ゼロで満たされたdtype longの行列を作成

In [0]:
x = torch.rand(5,3)
print(x)

tensor([[0.4347, 0.4686, 0.0504],
        [0.8591, 0.8385, 0.7416],
        [0.5997, 0.9111, 0.7338],
        [0.7620, 0.7617, 0.6567],
        [0.3580, 0.7865, 0.0911]])


In [0]:
# データから直接テンソルを作成

In [0]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
# 既存のテンソルに基づいてテンソルを作成
# これらのメソッドは、ユーザーが新しい値を提供しない限り、dtypeなどの入力テンソルのプロパティを再利用

In [0]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [0]:
x = x.new_ones(5, 3, dtype=torch.double) 
print(x)

x = torch.randn_like(x, dtype=torch.float) 
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-2.2236,  0.6814, -1.3830],
        [-0.6347,  0.8413,  0.0624],
        [ 1.1628, -0.3660,  1.6328],
        [-0.9798, -0.8820, -1.2398],
        [-0.4726,  0.0219, -0.1322]])


In [0]:
# サイズを取得

In [0]:
print(x.size())

torch.Size([5, 3])


In [0]:
# 加算演算

In [0]:
y = torch.rand(5,3)
print(x + y)

print(torch.add(x, y))

tensor([[-2.1567,  0.6913, -0.5979],
        [-0.2263,  1.6730,  0.2510],
        [ 1.7936,  0.2278,  2.3427],
        [-0.0366, -0.7760, -1.1362],
        [ 0.4453,  0.8247,  0.4906]])
tensor([[-2.1567,  0.6913, -0.5979],
        [-0.2263,  1.6730,  0.2510],
        [ 1.7936,  0.2278,  2.3427],
        [-0.0366, -0.7760, -1.1362],
        [ 0.4453,  0.8247,  0.4906]])


In [0]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-2.1567,  0.6913, -0.5979],
        [-0.2263,  1.6730,  0.2510],
        [ 1.7936,  0.2278,  2.3427],
        [-0.0366, -0.7760, -1.1362],
        [ 0.4453,  0.8247,  0.4906]])


In [0]:
# 追加：インプレース

In [0]:
y.add_(x)
print(y)

tensor([[-2.1567,  0.6913, -0.5979],
        [-0.2263,  1.6730,  0.2510],
        [ 1.7936,  0.2278,  2.3427],
        [-0.0366, -0.7760, -1.1362],
        [ 0.4453,  0.8247,  0.4906]])


In [0]:
# すべてのベルとホイッスルで標準のNumPyのようなインデックスを使用

In [0]:
print(x[:, 1])

tensor([ 0.6814,  0.8413, -0.3660, -0.8820,  0.0219])


In [0]:
# サイズ変更torch.view：テンソルのサイズを変更/変更したい場合

In [0]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [0]:
# 1要素のテンソルがある場合.item()、Pythonの数値として値を取得するために使用

In [0]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.8698])
0.8698033094406128


In [0]:
# トーチテンソルをNumPy配列に変換する

In [0]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [0]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [0]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [0]:
# NumPy配列をトーチテンソルに変換する

In [0]:
import numpy as np

In [0]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [0]:
# CUDAテンソル

In [0]:
# テンソルは、この.to方法を使用して任意のデバイスに移動

In [0]:
if torch.cuda.is_available():
   device = torch.device('cuda')
   y  = torch.ones_like(x , device=device)
   x = x.to(device)
   z = x + y
   print(z)
   print(z.to('cpu',torch.double))